---
# tasks file for nginx
- name: Install nginx server for RHEL 8
  import_tasks: redhat-8.yml
  when:
   - ansible_facts['os_family']|lower == 'redhat'
   - ansible_facts['distribution_major_version']|int >= 8

- name: Install nginx server for RHEL 7
  import_tasks: redhat-7.yml
  when:
   - ansible_facts['os_family']|lower == 'redhat'
   - ansible_facts['distribution_major_version']|int <= 7

- name: Install nginx server for Debian
  import_tasks: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'

- name: Make sure nginx is running
  ansible.builtin.systemd:
    name: nginx
    enabled: yes
    state: started
